// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using FirstLibrary.Core.Common;
using System;
using System.Collections.Generic;

namespace FirstDemo.Data.Models;


public class OrderDetailKey
{
    public int OrderId { get; set; }

    public int ProductId { get; set; }
}

public partial class OrderDetail : IEntity<int>
{
    public int Id { get; set; } 
    public int OrderId { get; set; }

    public int ProductId { get; set; }

    public decimal UnitPrice { get; set; }

    public short Quantity { get; set; }

    public float Discount { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }
    //public OrderDetailKey Id { get ; set ; }
}