<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.2.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>b7cc7ae0-618a-49ac-a3b5-92244999e7f0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FirstDemo.API\FirstDemo.API.csproj" />
    <ProjectReference Include="..\FirstDemo.BLazor.Server\FirstDemo.BLazor.Server.csproj" />
  </ItemGroup>

</Project>
